version: '3.8'

services:
  pg-isiimg:
    container_name: pg-docker
    image: postgres:latest
    hostname: pg-docker
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: messagerie
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - kafka_network

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    networks:
      - kafka_network

  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - broker
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      sleep 15 &&
      kafka-topics --create --if-not-exists --bootstrap-server broker:19092 --topic topictechout --replication-factor 1 --partitions 1 &&
      kafka-topics --create --if-not-exists --bootstrap-server broker:19092 --topic topictechin --replication-factor 1 --partitions 1 &&
      kafka-topics --create --if-not-exists --bootstrap-server broker:19092 --topic topicout --replication-factor 1 --partitions 1 &&
      kafka-topics --create --if-not-exists --bootstrap-server broker:19092 --topic topicin --replication-factor 1 --partitions 1
      "
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

volumes:
  pgdata:

